### ISSUE TITLE
Job not working

### ISSUE THREAD

**Issue by Fanatic191** [ShakirPlayZ/job-activate-power#1]
Hy, i added this to my Athena server, tried to start the job, but i only have to collect cars, i cant fix the lights with this job. 

It would be better, if admins can turn on and off this plugin. I like it. Thanks

**Comment by ShakirPlayZ** [comment]
I dont understand your comment.
This plugin is about turning the City lights on.

I will add a config file for the blips and some other settings


Thanks

**Comment by Fanatic191** [comment]
Hy ShakirPlayZ. 

After i logged into the game, the power is off. I checked the .ts files, but i did not find what do i have to do to repair the power outage. 
I tried to write a command for that, with permissions for administrators to turn of or turn on manually, not just with the job. 

Anyway, thank you so much for that plugin, it is awesome! :)

**Comment by ShakirPlayZ** [comment]
Hey,

just updated the Code.
Added Commands and a config file.

Did not test everything. Please Test it for me and give me a Feedback.

**Comment by Fanatic191** [comment]
You are awesome! Commands are working well, thank you so much for your help and for the correction. I can see the blip on the map and can start the job too. :)
